source :gemcutter

gem "nokogiri"
gem "builder"
gem "rainbows"
gem "system_timer"
gem "cramp"
gem "uuid"
gem "carrot"
gem "validatable"
gem "memcachedb-client", "0.0.2"
gem "usher"
gem 'newrelic_rpm', :require => false
gem "rack-test"
gem 'exceptional'