#!/bin/bash
### BEGIN INIT INFO
# Provides:          bfeature
# Required-Start:    $memcachedb $rabbitmq
# Required-Stop:     $memcachedb $rabbitmq
# Default-Start:     2 3 4 5 S
# Default-Stop:      0 1 6
# Short-Description: bfeature
# Description:       bfeature
### END INIT INFO
#
# Init file for Bolide instances
#
# description: Bolide instances
#

# source function library
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions

RETVAL=0
prog="Bolide feature"

# Some functions to make the below more readable

start()
{
        echo $"Starting..."

       	echo -n "Feature App"
        cd "/u/apps/bolide/current/feature_app"
        [ -f tmp/pids/unicorn.pid ] && echo ": already started!"
        /usr/bin/unicorn_rails  -c ../config/server/app/www.bolideapp.com.rb -E production -D && echo ": OK"
		
        echo "done"
}

stop()
{
        echo $"Stopping..."

				echo -n "Feature App"
				kill -QUIT `cat /u/apps/bolide/current/feature_app/tmp/pids/unicorn.pid` && echo ": OK" || echo ": failed";
       	rm "/u/apps/bolide/current/feature_app/tmp/pids/unicorn.pid"

        echo "done"
}

restart()
{
        echo $"Reloading..."

        echo -n "Feature App"
				kill -USR2 `cat /u/apps/bolide/current/feature_app/tmp/pids/unicorn.pid` && echo ": OK" || echo ": failed";
  				
        echo "done"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
exit $RETVAL