#!/bin/bash
#
# Init file for Bolide instances
#
# description: Bolide instances
#

# source function library
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions

RETVAL=0
prog="Bolide Helpers"

# Some functions to make the below more readable

start()
{
        echo $"Starting..."

       	echo -n "bstat"
        cd "/u/apps/bolide/current/helpers"
        /usr/bin/ruby helpers.rb start bstat && echo ": OK"
				
        echo "done"
}

stop()
{
        echo $"Stopping..."

				echo -n "bstat"
        cd "/u/apps/bolide/current/helpers"
        /usr/bin/ruby helpers.rb stop bstat && echo ": OK"
				
        echo "done"
}

restart()
{
        echo $"Reloading..."

        echo -n "bstat"
        cd "/u/apps/bolide/current/helpers"
        /usr/bin/ruby helpers.rb restart bstat && echo ": OK"
				
        echo "done"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
exit $RETVAL