#!/bin/bash
### BEGIN INIT INFO
# Provides:          bstream
# Required-Start:    $memcachedb $rabbitmq
# Required-Stop:     $memcachedb $rabbitmq
# Default-Start:     2 3 4 5 S
# Default-Stop:      0 1 6
# Short-Description: bstream
# Description:       bstream
### END INIT INFO
#
# Init file for Bolide instances
#
# description: Bolide instances
#

# source function library
[ -f /etc/rc.d/init.d/functions ] && . /etc/rc.d/init.d/functions

RETVAL=0
prog="Bolide stream"

# Some functions to make the below more readable

start()
{
        echo $"Starting..."

				echo -n "Stream App"
        cd "/u/apps/bolide/current/stream_app"
        [ -f tmp/pids/live.unicorn.pid ] && echo ": already started!"
        /usr/bin/rainbows  -c ../config/server/app/live.bolideapp.com.rb -E production -D && echo ": OK"	
				
        echo "done"
}

stop()
{
        echo $"Stopping..."

				echo -n "Stream App"
				kill -QUIT `cat /u/apps/bolide/current/stream_app/tmp/pids/live.unicorn.pid` && echo ": OK" || echo ": failed";
				rm "/u/apps/bolide/current/stream_app/tmp/pids/live.unicorn.pid"

        echo "done"
}

restart()
{
        echo $"Reloading..."

				echo -n "Stream App"
				kill -USR2 `cat /u/apps/bolide/current/stream_app/tmp/pids/live.unicorn.pid` && echo ": OK" || echo ": failed";
				
        echo "done"
}

case "$1" in
        start)
                start
                ;;
        stop)
                stop
                ;;
        restart)
                restart
                ;;
        *)
                echo $"Usage: $0 {start|stop|restart}"
                RETVAL=1
esac
exit $RETVAL