development:
  adapter: mysql
  database: development
  username: root
  password: mysql
  
production:
  adapter: mysql
  database: production
  socket: /var/run/mysqld/mysqld.sock
  username: root
  password: mysql