development:
  :address: smtp.sendgrid.net
  :port: 25
  :domain: bolideapp.com
  :authentication: login
  :user_name: julien.guimont@gmail.com
  :password: Kaiser11
production:
  :address: smtp.sendgrid.net
  :port: 25
  :domain: bolideapp.com
  :authentication: login
  :user_name: julien.guimont@gmail.com
  :password: Kaiser11