development:
  :address: smtp.sendgrid.net
  :port: 25
  :hostname: bolideapp.com
  :authentication: plain
  :user_name: julien.guimont@gmail.com
  :password: Kaiser11
production:
  :address: smtp.sendgrid.net
  :port: 25
  :hostname: bolideapp.com
  :authentication: plain
  :user_name: julien.guimont@gmail.com
  :password: Kaiser11